### ISSUE TITLE
Asset precompilation for Docker in production mode

### ISSUE THREAD

**Issue by mskog** [cantino/huginn#1119]
I ran into issues with using the Docker image in production mode because it doesn't do any assets precompilation in the init script thus no assets are served.

It is of course easily fixed by doing something like `sudo -u huginn -EH bundle exec rake assets:precompile` (in production mode only) in the init script and then set the `RAILS_SERVE_STATIC_FILES` env variable to make Rails serve the files.

Is this something that you've thought about doing or am I confused here? I can do a PR with this if this is what you prefer.

The good news is that it works just fine now!

**Comment by cantino** [comment]
Hey @mskog, thanks!  I don't use Docker personally, but I know @dsander and @ianblenke do.  They may know what our standard approach is.

**Comment by dsander** [comment]
Hi @mskog, the process you are describing sounds about right. I am not using the docker container in production myself because I did not know the "right" way to dockerize a rails application for production. I figure one wants one container per service (nginx, unicorn and n background workers), then there was the question on how to make the compiled assets available to nginx and how to do deployment without manually stopping, pulling and restarting a bunch of containers.
Somewhere around the process I gave up kept my capistrano deployment process.

**Comment by kennethkalmer** [comment]
The new containers in #1204 does precompile the assets.

**Comment by mskog** [comment]
> The new containers in #1204 does precompile the assets.

Excellent!

**Comment by dsander** [comment]
Thanks for the reminder @kennethkalmer, closing this.
