### ISSUE TITLE
Remove BOM by default in Website Agent

### ISSUE THREAD

**Issue by HyShai** [cantino/huginn#1137]
When a response has a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) the `parse` method of the Website Agent chokes - specifically the `JSON.parse(data)` call. Perhaps it would a good idea to remove the BOM (by default) before trying to parse it. This can either be done somewhere  in `website_agent.rb` e.g.:

<pre>
#line 472
when "json"
        <b>JSON.parse(data.sub!(/^\xEF\xBB\xBF/, ''))</b>
</pre>
or somewhere in `web_request_concern.rb` e.g.:

<pre>
#line 43
when /\A\s*(?:text\/[^\s;]+|application\/(?:[^\s;]+\+)?(?:xml|json))\s*(?:;|\z)/i
            encoding = @default_encoding
            <b>body = body.sub!(/^\xEF\xBB\xBF/, '')</b>
</pre>

As an aside, this is a scenario where it would be really useful for the Website Agent to have the ability to extract from an event payload (#1050). E.g. prior to parsing the response with JSONPath we would be able to remove the BOM with Regex and then pass the response back to the WebsiteAgent to make use of JSONPath. (While the Javascript agent can parse JSON - it doesn't have the full capabilities of JSONPath without writing a lot of code.) 

Another idea would be to extract (pun!) the parsing aspect of the WebsiteAgent into its own agent - __ParsingAgent__. That way the WebsiteAgent would only have to do one thing - _get the response of a url_. And the Parsing Agent would have the various parsing responsibilities and capabilities - encoding etc., JSON, XML, HTML, text etc. This would have the added benefit of being able to use Nokogiri and JSONPath on arbitrary data (that isn't necessarily a _direct_ response of a url request.)

**Comment by knu** [comment]
While there's a room we may support it, I don't think JSON has ever allowed BOM since it's born, so any data source that serves JSON with a BOM should be fixed.  JSON was born as a subset of JavaScript, in which the existence of a BOM would simply make a snippet invalid as a program.  [The very first RFC](](https://tools.ietf.org/html/rfc4627#section-3)) which most existing implementations still follow has no mention of BOM indicating there should be no BOM since the encoding of a JSON file can be determined by reading the first few bytes without the need for a BOM, and [the latest RFC](https://tools.ietf.org/html/rfc7159#section-8.1) explicitly prohibits implementations for adding a BOM.

**Comment by HyShai** [comment]
@knu Yup, that make sense. I guess having the ability to "pre-process" a response before sending it to Nokogiri and JSONPath would be the best way to tackle an issue like this. I had 2 idea (above) how to do this - either a new ParsingAgent or allow the WebsiteAgent to use an event payload. What do you think?

**Comment by knu** [comment]
Perhaps the not so run-time efficient but easiest way to achieve it would be to add a Liquid function to compose a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) from a Content-Type and data for use in `url_from_event`, and then add ability to scrape a data out of a data URI to WebsiteAgent.  This way WebsiteAgent would only have to deal with URLs as source of data.

**Comment by knu** [comment]
Of course we could just add a `content_from_event` option instead and refactor `check_urls` and `check_url`.

**Comment by cantino** [comment]
This is done now, at least the part about adding `data_from_event`.
