### ISSUE TITLE
Install SSL 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1186]
Using Debian 8.1 x64 in DigitalOcean.

If someone could give instruction on how SSL should be properly installed on huginn appreciate it. Trying to use StartSSL Free. https://www.startssl.com/Support?v=1

**Comment by mikalauskas** [comment]
I'm using this one nginx conf https://github.com/cantino/huginn/blob/master/deployment/nginx/huginn-ssl

**Comment by signallhill** [comment]
The self signed one is not recommended. Browser stops me from going to the website saying ssl is not trusted.

**Comment by cantino** [comment]
@signallhill, yes, self-signed will cause the browser to warn, but since you created the cert, you can confirm it and tell the browser to continue.  Obviously this isn't a good practice unless you know a site is using a self-signed cert, since it could be someone messing with the traffic.

**Comment by signallhill** [comment]
@cantino so that will not expose my credentials and data?

**Comment by virtadpt** [comment]
It will not, no.  Your browser (Firefox, I'm guessing) is complaining because your Huginn instance's SSL certificate wasn't issued by any of the CA's that it knows about (it's self-signed).  It's trying to protect you by not letting you access your own site, which is the wrong thing to do.  You can either open a private browsing window and log into Huginn (Firefox will let you do that), or you can try Chrome or Chromium (which will complain but give you the option to proceed anyway).

**Comment by signallhill** [comment]
Thanks
