### ISSUE TITLE
Agents not automatically updating on server

### ISSUE THREAD

**Issue by sthc8** [cantino/huginn#1233]
Recently, my agents on Huginn have stopped automatically updating. 

I created an RssAgent that grabbed ~25 feeds, along with another 20 separate RssAgents. When I noticed it stopped updating, I deleted all the separate RssAgents (and the default agents). Still wasn't updating.

Thinking I had too many agents running, I left the one RssAgent and one DataOutput agent, deleting most of the feeds and only leaving 3, figuring this is a light job to test. 

The agent works when I manually hit run, grabbing events correctly, but just doesn't update automatically on schedule (I've tested different time periods, every 12hr, every 1hr, 30 min). In addition, I've deleted all past events and logs. When the job runs, there isn't a massive delay, about 300 events are created. 

Huginn is installed on the free AWS tier. I've read some past issue threads. One talked about a memory leak, but I checked my server logs and everything seems to be fine. Another thread talked about too many agents running, but I have since deleted almost all and only left 2 running.

Not sure what else to do. Thanks.

**Comment by dsander** [comment]
Hi @sthc8,

since you mentioned you run on the AWS free tier you probably are using the [threaded background workers](https://github.com/cantino/huginn/blob/master/Procfile#L24-L25)? The problem you are describing sounds like the HuginnScheduler somehow stopped working but DelayedJob ist still processing jobs you manually trigger via the run command.

Did you try to restart huginn? `bundle exec rake production:restart` if you used the manual installation guide.

If that does not help can you check the [logs](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#rails-application-log-homehuginnhuginnlogproductionlog) for errors or exception?

**Comment by sthc8** [comment]
Got it working again! Thanks a bunch dsander

I'm not too familiar with AWS / server-side things, so I went in and restarted. I looked through the logs but didn't see any Delayed Jobs, but this was just going through AWS console and not through the command line.

For future reference, how can I prevent this from happening again? Is it because I had too many agents running and the free-AWS tier can't handle that many jobs?

**Comment by dsander** [comment]
It is possible that something got killed because the machine ran out of memory. This command should output something if it happened: `grep -i 'killed process' /var/log/messages`

With no exception or error message it is hard to guess what went wrong, the 1GB of RAM the ` t2.micro` instance offers should be enough for huginn. I can only suggest to have a look at the  [logs](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#rails-application-log-homehuginnhuginnlogproductionlog) when you notice huginn acting strange again.

**Comment by sthc8** [comment]
Thanks again dsander. Hopefully it doesn't happen again, but if it does, I'll learn how to dig around the logs.
