### ISSUE TITLE
rake db:create error

### ISSUE THREAD

**Issue by loganfreeman** [cantino/huginn#1288]
```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>10, "username"=>"hugin", "password"=>"hugin", "host"=>nil, "port"=>nil, "socket"=>"/tmp/mysql.sock", "strict"=>false}
```

mysql2 (0.3.20)

**Comment by cantino** [comment]
Did you get any other error information?

**Comment by BinaryPaean** [comment]
@loganfreeman 

If you are using docker, this /may/ be related to a very similar problem I ran into, which is that the override/priority order for the database connector env vars are a little confusing.

In my situation, when I [linked a postgres docker container](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) to the huginn container, and then specified some additional environmental variables in the docker run string as in [the docker usage example](https://hub.docker.com/r/cantino/huginn/), and THEN had the default db information from the [example env file](https://github.com/cantino/huginn/blob/master/.env.example), the db:seed operation kept defaulting to localhost rather than the injected host address for the database.

The best fix is to just not be as confused as I was.

The second best fix seems to be to put all the database environmental variables into your env file for docker, and ensure the host points to the network docker name you're importing.

If you're not using a dockerized db, then its probably something else.

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
