### ISSUE TITLE
Foreman ignores $PORT variable, always uses 5000

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1291]
Has anyone else seen this?  No matter what I put in the `.env` file for `PORT`, it always uses port 5000.  When I added a debugging line to my Procfile

```
blah: echo `env`
```

It shows that Foreman is setting PORT=5000.  Looks like Foreman has issues for this: https://github.com/ddollar/foreman/issues/167 and https://github.com/ddollar/foreman/issues/583

This can be overridden with `foreman start -p 3000`.

@dsander, do you think we should standardize on port 5000 in Docker and remove the ineffective defaulting in the Procfile, or have Docker use the `-p` option, or something?

**Comment by dsander** [comment]
I noticed it too, but did not investigate yet. Defaulting to port 5000 is not really an option, it would require every docker user to change the `docker run` command to adapt the new exposed port.
The easiest solution would probably be to change our documentation to include the `-p` flag.

**Comment by cantino** [comment]
So Docker is assuming port 5000, I gather?

**Comment by dsander** [comment]
No, docker is assuming port 3000. If we change that every docker user has to change how they launch the container.

**Comment by cantino** [comment]
Hmm, then I don't fully understand how it's working inside Docker.  Wouldn't foreman be setting it to 5000 unless we're using the `-p` option?

**Comment by dsander** [comment]
This only applied to the `huginn` image, the single process one does not use foreman at all. We still try to change the [Procfile](https://github.com/cantino/huginn/blob/master/docker/multi-process/scripts/init#L194), but that does not work anymore because the regex is outdated. It does not cause issues because the next line exports `PORT` which will be used by foreman (this works because `PORT` is a real env variable and not loaded by `dotenv-rails` after foreman booted).

**Comment by TildeWill** [comment]
Jumping in because this could be related to pull request #1082 I initiated. The change in that request pulls from an env variable `$PORT`, and if that's missing, fills in port 3000, which seems like the desired behavior. The regex in docker init shouldn't be needed anymore if I understand everything correctly since that regex looks to be trying to add support for specifying the port via env variable.

I wouldn't expect changes made to `.env` to make a difference because as @dsander says, the `.env` file gets loaded by rails which happens after the call to start the server. If you wanted to use you .env file, then the foreman issue suggests you might be able to use the foreman argument `-e .env`, but would mean another change to the Procfile.

**Comment by cantino** [comment]
Foreman should be loading the `.env` file automatically, that's the origin of `.env`, I think?  But it ignores the PORT variable in the file.

**Comment by TildeWill** [comment]
TIL that I've been needlessly dropping in the dot env gem. Gracias!

**Comment by dsander** [comment]
@cantino Aha! I also totally ignored that foreman loads the `.env` file. So the problem is we do not specify `PORT` in our `.env` file? When I add it it seems to work as expected.

**Comment by cantino** [comment]
Whoops, I guess it is that simple.  Do you see any downsides to #1298?  Will it affect Docker or your deployment guide?
