### ISSUE TITLE
Batch Re-emit

### ISSUE THREAD

**Issue by vmpj** [cantino/huginn#1344]
Is it possible to do a batch re-emit events that was generated by a agent?

I can see how to re-emit one event, but how a about the last 100, or all of them.

Thanks.

**Comment by dsander** [comment]
Hi @vmpj,

we do not have an option to do that via the web interface. In a rails console you can do it like so:

```
# All Events:
Event.all.each(&:reemit!)
# The last 100
Event.order('id DESC').limit(100).each(&:reemit!)
# All of an agent
Agent.find(1).events.each(&:reemit!)
```

**Comment by vmpj** [comment]
Great, that did the trick!
Thanks

**Comment by waldens** [comment]
@dsander I tried `Agent.find(x).events.each(&:reemit!)`, which x is the ID of agent, right?
It falls into a infinite loop of re-emit. 
I thought if Agent has 50 events now, this command will only re-emit these 50 events ONCE.

Nothing error message I can see in console, it's just infinite 
`Enqueued AgentReceiveJob (Job ID: 7d9e4352-aa82-41c6-a6bd-f28a13802aaf) to DelayedJob(default) with arguments: 93, [108546]`
until pressing CRTL-C.

**Comment by cantino** [comment]
It shouldn't be an infinite loop, but it should re-emit every event that Agent#x has ever created, and it'll load them into RAM immediately, which could be slow or crash.

You could do:

```ruby
agent = Agent.find(x)
events = agent.events.first(50).to_a
events.each do |event|
  event.reemit!
end
```

But what are you trying to achieve?

**Comment by waldens** [comment]
@cantino
On my Huginn instance, agent#x had 50 events, and once this command was executed, almost 2000 jobs were created in about 10 seconds, and continued to increase.

Want to batch re-emit just because I am too lazy to re-GET these events again, and also afraid of being banned by target website for GET frequently.

However, just passing by, give some feedback. In fact not a serious problem. 😊
