### ISSUE TITLE
Nitrous quickstart button link broken

### ISSUE THREAD

**Issue by rpglover64** [cantino/huginn#1459]
It doesn't seem to have a `repo` parameter, which quickstart appears to require.

**Comment by dsander** [comment]
Hi @rpglover64,

I am redirected to the correct URL including a `repo` param, but then I am getting an error: "Another container creation request is currently being processed".

@yeouchien Can you please have a look what is going wrong?

**Comment by yeouchien** [comment]
Hi @rpglover64,
Nitrous quickstart doesn't require a `repo` param if it's click from repo `README` file. It will just use `HTTP referer`. 

@dsander I've tested it again and it works fine for me. Did you click the button twice? That error indicate that your workstation is creating another project. Workstation can only create 1 project at a time.

**Comment by dsander** [comment]
@yeouchien Thanks, I don't know what went wrong. I had to log in to my nitrous after clicking the quickstart button, then get the "resuming workspace" message but did not see the "launching application" dialog. When I checked it this morning I got one application running.

Is it possible the quickstart button is not working if the browser is not sending the HTTP referrer (maybe caused by strict do-not-track settings/addons)?

**Comment by yeouchien** [comment]
@dsander, Nitrous free workspace is supposed to go idle when inactive. Quickstart process will be continued after a workspace is started. HTTP referer shouldn't be a problem here. 😃

**Comment by dsander** [comment]
@yeouchien Thanks for the clarification. 

@rpglover64 Does the quickstart button work for you now?

**Comment by rpglover64** [comment]
Still does not work, in either Vivaldi or Firefox.

I'm getting:

    {"error":"invalid_request","error_description":"Invalid repository URL"}

In both browsers, I am running PrivacyBadger and uMatrix and setting the do-not-track option.

**Comment by dsander** [comment]
@rpglover64 I was able to reproduce it by installed an extension that blocks the `Referer` header, I added the `repo` to the link, it should work now.
