### ISSUE TITLE
Strange installation + libv8 install does not finish

### ISSUE THREAD

**Issue by KuenzelIT** [cantino/huginn#1467]
Hey,

I'm just trying to install Huginn on a RaspberryPi2. So far everything was fine until installing the gems. There the installation stopped every 10-20 gems. I then had to stop and restart it and again the next 10-20 gems were installed.

Now it is stuck here: 
`Installing libv8 3.16.14.13 with native extensions`

Does not get any further even with restarting the installation.

Does anyone have a clue what's wrong here?

Unfortunately I don't have any experience with ruby at ALL. :)

**Comment by KuenzelIT** [comment]
Alright, it took like an hour to finish installing libv8. If that's normal, then there is no issue with that.

Still kind of strange that other gems took so long that I restarted and then they were installed in 2 seconds.

**Comment by dsander** [comment]
Hi @KuenzelIT,

I think the installation took that long because it needed to compile libv8 on the raspberry due to missing binary packages. An hour is really long, but giving the low processing power it sounds possible. After the gems installed (and possibly build their native C extensions) `bundle install` will finish fast because all gems are already installed.

**Comment by KuenzelIT** [comment]
Hey,
thanks for your quick response, that might be it.

The only question left is why it got stuck on some gems and installed them right away after I restarted the installation.

**Comment by dsander** [comment]
That is a good question, the reason could be the same even though its unlikely that the timing was right multiple times.
