### ISSUE TITLE
Question about api authentication choice in google_calendar_publish_agent.rb

### ISSUE THREAD

**Issue by bleakstew** [cantino/huginn#1867]
I am planning on using the Google Calendar Agent as a template for an agent to save files to Google Drive. I was wondering if anyone knew why the choice was made to authenticate with Google API using a service account rather than OAuth. It looks like this approach requires that the Huginn user configuring the agent has to have shell access to the application server in order to save the API key. It seems like it would be better to allow the user to complete agent configuration entirely within the Huginn user interface, maybe by using a Huginn credential?

I'm a novice with Ruby and developing against service APIs, so maybe this is obvious. I'm just wondering if I should copy the Calendar Publish authentication strategy or shoot for something better. Thanks.

**Comment by cantino** [comment]
Hey @bleakstew, that's a good question. @CloCkWeRX may remember why it was implemented that way. It's possible that we didn't have a good OAuth solution yet? It does look like you can use a credential via Liquid instead of a key file on disk, so it doesn't require shell access to the application server. If OAuth works, that does seem a bit better to me, although Google likes their Service accounts.

**Comment by CloCkWeRX** [comment]
https://developers.google.com/identity/protocols/OAuth2ServiceAccount

Most of the automation tends to fall into the
> Your application calls Google APIs on behalf of the service account, so users aren't directly involved. 

bucket.

**Comment by bleakstew** [comment]
Thanks for the info
