### ISSUE TITLE
Events payload sent from Digest Agent not accessible within Data Output Agent

### ISSUE THREAD

**Issue by axsuul** [cantino/huginn#1963]
It looks like within the payload that a **Digest Agent** sends, in addition to `message` there is also an `events` key pertaining the all the events that the Digest Agent has captured. I have a **Data Output Agent** that then receives this payload but I'm having trouble accessing the `events` within the payload. I can access `message` no problem. Here's the portion of my **Data Output Agent** config:

```json
"template": {
    "title": "Feed",
    "description": "test feed",
    "item": {
      "title": "Test",
      "description": "{{ events }} <ul>{% for event in events %}<li><a href='{{ event.query_url }}'>{{ event}}</a></li>{% endfor %}</ul>"
    }
  }
```

The value for `description` is instead returning

```
#<Event:0x000000047c6c90> <ul><li><a href=''>#<Event:0x000000047c6c90></a></li><li><a href=''>#<Event:0x000000047c71b8></a></li></ul>
```

What can I do to loop through all the events that the **Digest Agent* collects and sends over?

**Comment by dsander** [comment]
@axsuul The problem is that the `DataOutputAgent` [exposes its source event](https://github.com/cantino/huginn/blob/master/app/models/agents/data_output_agent.rb#L250) to Liquid which will also override the `events` when interpolating the items. 
You should be able to work around it by using a `EventFormattingAgent` to rename the `events` key in the Event to something else.

@knu Would it make sense to move the mutation of the `interpolation_context` after the [item interpolation block](https://github.com/cantino/huginn/blob/master/app/models/agents/data_output_agent.rb#L252-L266)? In theory one could also use the whole `events` data in individual items, but I don't see how it could be useful.

**Comment by axsuul** [comment]
@dsander Thanks so much for responding! I ended up using `EventFormattingAgent` but had to use a special liquid `as_object` filter to keep it as an array.

```json
{
  "instructions": {
    "date": "{{ 'now' | date: '%B %e, %Y' }}",
    "digest_events": "{{ events | as_object }}"
  },
  "matchers": [

  ],
  "mode": "clean"
}
```

**Comment by axsuul** [comment]
Closing this issue and opening up a new one: https://github.com/cantino/huginn/issues/1964

**Comment by knu** [comment]
@dsander @axsuul Just pushed a fix for this!

**Comment by dsander** [comment]
@knu Awesome thanks!

**Comment by axsuul** [comment]
@knu Thanks, that was quick :)
