### ISSUE TITLE
Extract and upgrade Chef deployment to work properly with CentOS, Ubuntu, Vagrant and Docker [BOUNTY]

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#416]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=3391727)](https://www.bountysource.com/issues/3391727-bounty-extract-and-upgrade-chef-deployment-to-work-properly-with-centos-ubuntu-vagrant-and-docker?utm_source=3391727&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Goals:

* Move Chef, Vagrant and Docker-related deployment files in `deployment/` to a new repository (https://github.com/cantino/huginn-chef)
* Recover anything useful from https://github.com/cantino/huginn/pull/339 and https://github.com/cantino/huginn/pull/377.
* Make Chef deployment more resilient
* Support at least Ubuntu and CentOS
* Allow testing in Vagrant
* Ensure Docker works
* Support both rvm and rbenv
* Support multiple runs/upgrades

This issue is a new tracking issue that replaces https://github.com/cantino/huginn/issues/373, https://github.com/cantino/huginn/issues/401, and https://github.com/cantino/huginn/issues/194.

**Comment by cantino** [comment]
Since we have a Docker build now and official deploy instructions, I'm going to close this.

**Comment by dsander** [comment]
@cantino Do you know what will happen with the bounties we posted?

**Comment by cantino** [comment]
That's a good question.  Maybe I can move them to a new issue?

**Comment by alias1** [comment]
Not 100%, but they may also get returned to us?

Sent from Outlook Mobile




On Sun, Feb 14, 2016 at 5:38 PM -0800, "Andrew Cantino" <notifications@github.com> wrote:












That's a good question.  Maybe I can move them to a new issue?

**Comment by dsander** [comment]
I only have a "claim bounty" button on the [bountysource](https://www.bountysource.com/issues/3391727-extract-and-upgrade-chef-deployment-to-work-properly-with-centos-ubuntu-vagrant-and-docker-bounty) page. @cantino do you have more options available?

**Comment by cantino** [comment]
I've sent an email to their support to find out.  If we can move it, is there a Docker or deployment issue we should move it to?

**Comment by dsander** [comment]
I don't think so, there is always room for improvement, but I am quite happy with the current images.

**Comment by elijah** [comment]
It would be cool to be able to apply them to something that makes
deployments better overall - that's what makes them valuable.  :)

I personally think a lot of things around container deployment are still
VERY broken, philosophically - it would be Super if someone could convince
me otherwise, though!

--e

**Comment by alias1** [comment]
Personally I wouldn't mind an officially maintained unraid template. Some pretty basic xml and a GitHub repo wrapped around the docker image, probably an hour or so work at most if you already know how to setup the docker easily. But.. Busy/lazy..
Sent from Outlook Mobile




On Tue, Feb 16, 2016 at 1:28 PM -0800, "Elijah Wright" <notifications@github.com> wrote:










It would be cool to be able to apply them to something that makes

deployments better overall - that's what makes them valuable.  :)



I personally think a lot of things around container deployment are still

VERY broken, philosophically - it would be Super if someone could convince

me otherwise, though!



--e





On Tue, Feb 16, 2016 at 3:12 PM, Dominik Sander <notifications@github.com>

wrote:

**Comment by cantino** [comment]
Refunded all bounty placers and moved my portion to https://github.com/cantino/huginn/issues/166 and 
https://github.com/cantino/huginn/issues/1121.
