### ISSUE TITLE
Should Data Output Agent use CDATA for XML feeds? Or not escape at all?

### ISSUE THREAD

**Issue by spdustin** [cantino/huginn#456]
In the Data Output Agent, when receiving an XML feed of events, special HTML characters are escaped in the body of an XML element. Should this show the raw HTML, or perhaps wrap in a CDATA instruction?

**Comment by lienas** [comment]
Hi,
I am currently testing Huginn as replacement for **Yahoo Pipes**. I want to fetch different RSS-feeds, filter them for relevant keywords and create a merged RSS-feed to publish on our website. 
So far -so good.
My Problem is the following. The description of the fetched feeds is insite an CDATA Block. Whe using the **Data Out Put Agent** the CDATA-Tag gets escaped. Instead of  `<![CDATA[` I get `&lt;![CDATA[`.
How do I get that fixed ?
THX in advance!
Thomas

**Comment by cantino** [comment]
You could either strip them out in an EventFormattingAgent, or we could try to remove them automatically in the RSSAgent.  Does #957 work better for you by any chance?

**Comment by lienas** [comment]
Hi Andrew,

RSS Agent works perfekt for me. Thanks.

Another question:
How can I filter more than 1 Field (currently my Filter works fort he title-I also would like to filter in description and categories. The filter should work with a logical or.

Thomas

Von: Andrew Cantino [mailto:notifications@github.com]
Gesendet: Montag, 21. September 2015 22:36
An: cantino/huginn <huginn@noreply.github.com>
Cc: Thomas Lucas <t.lucas@lienas.de>
Betreff: Re: [huginn] Should Data Output Agent use CDATA for XML feeds? Or not escape at all? (#456)


You could either strip them out in an EventFormattingAgent, or we could try to remove them automatically in the RSSAgent. Does #957<https://github.com/cantino/huginn/pull/957> work better for you by any chance?

**Comment by cantino** [comment]
Did you use that pull request, or just the normal RSSAgent directly?

What does your filter look like now?

**Comment by lienas** [comment]
I used the RSS Agent.
Currently the filter (TriggerAgent) looks the following:
`{
  "expected_receive_period_in_days": "1",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "cloud|saas|iaas|sourcing|outsourcing|provider|offshore|nearsshore|apple|IT-Services",
      "path": "title"
    }
  ],
  "message": "{{description}}"
}`
I would like to filter also inside description and category. So that the filter works this way:
Find feeds where **title** or **description** or **category** contains **cloud** or **saas** or ..

**Comment by lienas** [comment]
Hello,
I found a solution, but I  am not sure if that is Best Practice.
I user multiple TriggerAgents and forward the all event filtered by these enents tomthe "De Duplication Agent"

Is there a better way ?

**Comment by cantino** [comment]
Sounds reasonable.  What does the Diagram look like?

**Comment by lienas** [comment]
Here we are:
![screenshot-agent outsourcing de 2015-10-01 09-50-27](https://cloud.githubusercontent.com/assets/8291992/10215537/a273de62-6822-11e5-9222-0dfd6db476b0.png)
This approach works fine, but I think the ability to filter with the same set of keywords inside the TriggerAgent would be the better approach. This is because keywords fpr "Titel" ans "Beschreibung" are the same here. When I decide to modify the set of keywords, I must change them on multiple places.

I am missing the links in this diagram. It is an production envirement,. hosted on our own server.

**Comment by cantino** [comment]
Thanks for sharing, that makes sense.  I've added support for partial matches by setting `must_match` to something less than the total number of rules (like 1, for `OR`) in #1056.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
