### ISSUE TITLE
PostAgent + WebsiteAgent Combination

### ISSUE THREAD

**Issue by usualmischief** [cantino/huginn#479]
any chance of allowing PostAgent to parse the response and emit an event with the data similar to WebsiteAgent -or- allow WebsiteAgent to specify data to be sent with the request (also specifying the method / content type)?

**Comment by snappermorgan** [comment]
This is exactly the feature I was looking for as I do quite a lot of ETL work and post form lead generation to various brokers whose system responds with transaction IDs I have to capture and record. This one feature, the ability to add an extraction to the PostAgent would go far with my use case!

**Comment by cantino** [comment]
Interesting @snappermorgan!  Do you know enough Ruby to work on it?

**Comment by snappermorgan** [comment]
Alas, it has been at least 4 years since I wrote in Ruby and I have been focusing on my PHP, Node and Angular skills lately. I can read it, deploy it, diagnose it and fix it, but it would take some ramp up time and my code would be shamefully sloppy. Regardless of this, I am going to deploy Huginn and make it work for me. I am lucky that a lot of the systems I use also allow GET and since WebsiteAgent can receive events I can tailor a custom URL with querystrings and then use the built in extractor to grab the returned transaction ID. From there I can do whatever I need with it, even repost it to another server. My processes involve a lot of realtime form posting with results dictating other business processes. I've been doing custom coding to handle these business processes but Huginns looks like it will save me hours of repetitive one-off coding.

Thanks!

**Comment by cantino** [comment]
Also, I'd love to hear more about how you use Huginn!  Be sure to check out the PostAgent and WebHookAgent, these might be another good way to get data into Huginn.  If you do make improvements that you can contribute back, I'm happy to help code review them and get them into shape for inclusion.

**Comment by cantino** [comment]
This is possible now, I beleive.  Feel free to (re-)open an Issue if you want to discuss further!
