### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError

### ISSUE THREAD

**Issue by warcode** [cantino/huginn#690]
I run the docker container with the built-in mysql database.
The website works fine and everything runs as it should for a while.

Then suddenly my every 10 minutes job was last ran an hour ago.

Are the agents using up the mysql connection pool and breaking?

```
foreman stdout | 18:25:28 jobs.1 | { 70156281429160 rufus-scheduler intercepted an error:
foreman stdout | 18:25:28 jobs.1 |   70156281429160   job:
foreman stdout | 18:25:28 jobs.1 |   70156281429160     Rufus::Scheduler::EveryJob "2m" {}
18:25:28 jobs.1 |   70156281429160   error:
foreman stdout | 18:25:28 jobs.1 |   70156281429160     70156281429160
foreman stdout | 18:25:28 jobs.1 |   70156281429160     ActiveRecord::ConnectionTimeoutError
18:25:28 jobs.1 |   70156281429160     could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `acquire_connection'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
18:25:28 jobs.1 |   70156281429160       /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/lib/huginn_scheduler.rb:190:in `with_mutex'
18:25:28 jobs.1 |   70156281429160       /app/lib/huginn_scheduler.rb:151:in `run_schedule'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/lib/huginn_scheduler.rb:129:in `block (2 levels) in run!'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:233:in `call'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:233:in `do_call'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:257:in `do_trigger'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:299:in `block (3 levels) in start_work_thread'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:302:in `call'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:302:in `block (2 levels) in start_work_thread'
18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:288:in `loop'
foreman stdout | 18:25:28 jobs.1 |   70156281429160       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:288:in `block in start_work_thread'
18:25:28 jobs.1 |   70156281429160   tz:
```

**Comment by cantino** [comment]
@icblenke, do you have any idea about this?

**Comment by dsander** [comment]
Taking the docker container build out of the equation, `ActiveRecord::ConnectionTimeoutError` sounds like either the server is running at too much load (CPU wise) or ran out of memory (mysqld in the docker container got kill, even though I dont know if that is possible). Is either of those options possible @warcode?

**Comment by warcode** [comment]
The server is straight to hardware 6-core I7 with 6 gigs of ram.

Unless docker limits the amount of cpu and ram it uses by default I don't think its plausible.
I'll check if non-docker stuff from previous deployments is hiding on the server later today.

**Comment by warcode** [comment]
Removed everything that could be causing problems but it still happens. Load average is at 0.78 and used memory at ~25%.

I can use the website just fine, adding/removing/editing agents, so the mysqld should be alive.

From what I can see there are 8 threads, and the default connection pool limit is 5. But does that mean a hard limit on 5 connections in the context?

**Comment by cantino** [comment]
@icblenke, do you have any ideas?

**Comment by ianblenke** [comment]
Easy enough to run mysql external to the container, as mentioned in the [docker/README.md](https://github.com/ianblenke/huginn/blob/master/docker/README.md)

You can use "docker exec -ti {containername} /bin/bash -li" or [nsenter](https://github.com/jpetazzo/nsenter) to connect to a running container to obtain a shell "inside" that docker container's process namespace.  With this, you should be able to use standard mysql debugging techniques.

Running only the built-in mysql in the container isn't something I would recommend anyone do. The only reason it does that by default is so that huginn can be easily deployed with docker to evaluate it. By its nature, docker is immutable infrastructure. When a container is removed, so is the data residing on it. The only way to persist data is to use a linked container that never gets removed, or use a host volume exported to the docker container to use. As things stand, there are no backups inherent to the built-in mysql database, which is something critically important to any managed persistence layer.

Deploying huginn for any kind of "production" use really does require mysql run in an HA way, preferably on persistence nodes managed with a convergence tool (Chef, Puppet, Ansible, Salt, etc). If you're on AWS, strongly consider an RDS or Aurora instance, and let AWS help manage that persistence for you.

Running persistence on immutable infrastructure runs into fun CAP questions of quorum, and a willingness to replace component containers over time. [http://ian.blenke.com/immutable-infrastructure-persistence/](http://ian.blenke.com/immutable-infrastructure-persistence/) is my presentation on that topic at the Tampa Bay area Docker meetup this past month.

**Comment by cantino** [comment]
Thanks @ianblenke!

**Comment by ianblenke** [comment]
If issue #887 is valid, my earlier suggestion may not actually work as described.

**Comment by ianblenke** [comment]
PR #905 shows a `docker-compose.yml` example for running a separate mysql container.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
