### ISSUE TITLE
WebsiteAgent: Extract .//node() error

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#850]
Setting `value` to __.//node()__ seems to double up the extracted text (try it to see)

__Agent: test__
Type: Website Agent
```json
{
  "expected_update_period_in_days": "7",
  "url": "http://theoatmeal.com/blog/dogs_nazis_horses",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "css": "#blog .post_body",
      "value": ".//node()"
    }
  }
}
```

Whereas setting `value` to __normalize-space(.)__ extracts it correctly. I would expect __.//node()__ to just give me the html as is on the web page.

I'm wondering if I'm doing something wrong or if this is a bug.

**Comment by cantino** [comment]
Good question, and I'm not sure.  @knu, do you know?

**Comment by knu** [comment]
You should use either "./node()" or ".", with which you could get inner HTML or outer HTML, respectively.
".//node()" recursively recursively selects all nodes, so, for instance, applying it to a node `<a>x<u>y</u>z</a>` will generate a node set that consists of:

* `<a>x<u>y</u>z</a>`
* `x`
* `<u>y</u>`
* `y`
* `z`

And you'll get a string with all those stringified and concatenated.  That's why you see duplicates.

**Comment by irfancharania** [comment]
Yep, that did it. Thanks @knu!
Will you add it to the description in the side? I think it'd be helpful to just have a line stating that.

**Comment by cantino** [comment]
@irfancharania, would you be interested in updating the doc?

**Comment by irfancharania** [comment]
Sure I'll give it a shot.

I was also thinking I would add an example entry in the wiki for a typical
scenario I'm using it for :
Rss agent > trigger agent (for filtering) > website agent (for full text
fetch) > dataout agent (for full text rss)

**Comment by cantino** [comment]
That'd be great!  Maybe on the page for configuration examples?
