### ISSUE TITLE
Updating huginn with modified Gemfile

### ISSUE THREAD

**Issue by msenthilvel** [cantino/huginn#910]
Hello, you guys have been great and quick in resolving issues. This is more of a newbie question, since I am not really sure how to update huginn that is running in production mode. I could fetch it from upstream and merge it with my master but I am using modified Gemfile and Gemfile.lock with support for pg and unicorn(production) and am not sure if it'll affect in anyway. Would adding Gemfile & Gemfile.lock to .gitignore solve my problem ? 
If not, what would you recommend?

**Comment by dsander** [comment]
I am also using postgresql on my production installation, you can `export ON_HEROKU=true` to install both the unicorn and pg gem without having to change the default Gemfile. This also changes the logging behavior a bit since it enables the rails12factor gem. You would then find the huginn logs in `/var/log/upstart/huginn*` or the directory you specified with the `-l` parameter when exporting the upstart jobs.

The Gemfile and Gemfile.lock are important to keep track of the gem versions huginn uses. If you want to avoid the rails12_factor gem I suggest to check out both files from upstream, manually add the pg and unicorn gem to the Gemfile and run bundle install every time you want to update.

**Comment by msenthilvel** [comment]
So I guess ignoring Gemfile isn't really advisable but I wrote OpenRC compatible initd script referring upstart script exported through foreman, so I don't use either foreman export or upstart directly. I would try manually adding pg and unicorn gem every time I update and hope it doesn't interfere with the existing config.Thank you!

**Comment by cantino** [comment]
Is it ultimately running something like `bundle exec rails s` or `bundle exec unicorn` or something?

**Comment by msenthilvel** [comment]
yep, it runs old version of commands specified in Procfile for production mode ( unicorn, schedule.rb, twitter_stream.rb and delayed_job).

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
