### ISSUE TITLE
Huginn Reuse & Extensibility

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn#959]
I want to take @cantino up on [his offer to start a hosted Huginn business](https://twitter.com/tectonic/status/623523697177923584), but as of yet, Huginn is really built to standalone, and there are additions that would be needed to bring it into a hosted model that don't make sense in the open source code base. In that vein I'd like to propose pulling out the core of Huginn into a [Rails engine](http://guides.rubyonrails.org/engines.html). This would allow Huginn to be pulled into other apps as a plugin and overridden as needed, reducing the need to fork and diverge from this community. 

The rough boundary I'm suggesting for the engine is to have all the app functionality in the engine, and all the deployment functionality (Heroku, Capistrano, etc) in the wrapper application. I would hope it also makes it easier for potential contributors to navigate the code with a clean split between app and deployment. 

What does everyone else think of this as a first step? Is this worth moving ahead?

**Comment by cantino** [comment]
Welcome @TildeWill!  I'm curious what @dsander and @knu, among others, think about this.

**Comment by dsander** [comment]
Hey @TildeWill! To me that sounds a bit backwards, wouldn't you override Huginn by including a billing/hosting engine into it? I am a bit worried that making Huginn itself an engine would make the installation and development process more complex as it already is (especially for new users/developers)

**Comment by pivotal-rivals** [comment]
@dsander certainly could do it that way, but it's still hard to "just pull in" the latests Huginn changes. You'd have to at least modify the Huginn Gemfile to include the billing/hosting engine. There could be other top-level changes that the billing/hosted code would require that I'm not thinking of at the moment. The dev cycle to update Huginn would consist of replaying billing/hosting-specific code on top Huginn each time you wanted to pull it in, and hope there's no conflicts. 

I think installation pain should remain largely unchanged, since I'd expect to provide a shell app that includes the Huginn engine. I think the extra step would be to copy the engine migrations into the shell app, but Rails provides a rake task for this so the timestamps are copacetic. 

Development is mixed IMO. On one hand you get focus by splitting the feature code from the deployment code. But yes, anytime you're dealing with both engine and shell app, you're essentially looking at gem development at the same time as doing app development. 

The other advantage of an engine is devs could drop Huginn into their existing apps. I'm thinking especially about internal company portals where they'd like to offer this kind of automation to their employees in a familiar location.

**Comment by TildeWill** [comment]
EDIT: repost as self

@dsander certainly could do it that way, but it's still hard to "just pull in" the latests Huginn changes. You'd have to at least modify the Huginn Gemfile to include the billing/hosting engine. There could be other top-level changes that the billing/hosted code would require that I'm not thinking of at the moment. The dev cycle to update Huginn would consist of replaying billing/hosting-specific code on top Huginn each time you wanted to pull it in, and hope there's no conflicts.

I think installation pain should remain largely unchanged, since I'd expect to provide a shell app that includes the Huginn engine. I think the extra step would be to copy the engine migrations into the shell app, but Rails provides a rake task for this so the timestamps are copacetic.

Development is mixed IMO. On one hand you get focus by splitting the feature code from the deployment code. But yes, anytime you're dealing with both engine and shell app, you're essentially looking at gem development at the same time as doing app development.

The other advantage of an engine is devs could drop Huginn into their existing apps. I'm thinking especially about internal company portals where they'd like to offer this kind of automation to their employees in a familiar location.

**Comment by cantino** [comment]
I think, in the short term, turning Huginn into an Engine might be more maintenance than we're looking for right now.  How challenging do you think it'd be, from a hosting perspective, to have huginn as an upstream and rebase on to it any hosting-specific changes periodically?

**Comment by TildeWill** [comment]
Yeah, rebasing my changes on the open source upstream has been okay so far. Closing the issue.
