### ISSUE TITLE
Namespace prefix media on content is not defined.

### ISSUE THREAD

**Issue by AviOmicron** [cantino/huginn#960]
Hi,

as started in this issue: https://github.com/cantino/huginn/issues/916
there is a problem when using media:content in the DataOutputAgent. I used it as follows:

```
 "item": {
      "title": "{{title}}",
      "description": "{{description}}",
      "link": "{{url}}",
      "media:content": {
        "_attributes": {
          "url": "www.google.com"
        }
```

when I use ``` "media": { ``` it works just fine, however as soon as you change it to ``` "media:content": { ``` I get the error: "error on line 16 at column 21: Namespace prefix media on content is not defined
Below is a rendering of the page up to the first error."

MacOSX 10.10.4
Chrome 44.0.2403.125
Huginn installed on Heroku

![image](https://cloud.githubusercontent.com/assets/13383411/9132300/d8449730-3cf2-11e5-8b21-416dd258adbb.png)

**Comment by cantino** [comment]
It looks like we'd need to set the correct namespace in the output header to `<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">`.  Maybe we should allow an array of namespaces to declare?

**Comment by cantino** [comment]
You could try editing app/models/data_output_agent.rb and adding that to line 174.  If that fixes it for you, we could add it for everyone.

**Comment by AviOmicron** [comment]
I did it here is the message I am getting: 

This page contains the following errors:

error on line 4 at column 26: Namespace prefix atom on link is not defined
error on line 5 at column 12: Namespace prefix atom on icon is not defined
Below is a rendering of the page up to the first error.

I think we need to change something on line 176 and 177 as well. Do you know what we have to put in there? I will do some research on my side as well.

```
             <atom:link href=#{feed_url(secret: params['secret'], format: :xml).encode(xml: :attr)} rel="self" type="application/rss+xml" />
             <atom:icon>#{feed_icon.encode(xml: :text)}</atom:icon>
```

**Comment by cantino** [comment]
Oh, oops, we should leave the atom part in I think?  Does this work?

```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
```

Alternatively, can you use an `enclosure` instead of `media:content`?

**Comment by AviOmicron** [comment]
This works :)
Will do some more testing in the next few days to see if there is anything that does not work as intended.

**Comment by cantino** [comment]
Great!  I think we should add that to the codebase.  Would you be interested in sending a PR with that added?

**Comment by thiagotalma** [comment]
Hello @cantino

I have a similar problem.

I can not create an RSS agent for the url "http://imagens.globoradio.globo.com/cbn/podcast/comentaristas/arnaldo-jabor/arnaldo-jabor-o-comentario-de-arnaldo-jabor.xml" and all others with the same pattern.

I do not know if I'm doing something wrong or if there are any problems in the code.

You can give your opinion, please?

Best!

**Comment by cantino** [comment]
This issue is about data output, I believe @thiagotalma.  Would you mind seeing if https://github.com/cantino/huginn/pull/957 helps?  If so, we should get that PR merged. /cc @knu

**Comment by thiagotalma** [comment]
@cantino, Unfortunately I'm not able to test.

I do not have a development environment, I am trying to direct test on Heroku but is occurring encode error.

If possible, do the test, please.
The url is `http://imagens.globoradio.globo.com/cbn/podcast/comentaristas/arnaldo-jabor/arnaldo-jabor-o-comentario-de-arnaldo-jabor.xml`

**Comment by cantino** [comment]
I'll try to take a look at this soon.

**Comment by cantino** [comment]
Hey @thiagotalma, the encoding of this RSS feed looks to be non-UTF8.  Try adding `"force_encoding": "ISO-8859-1"` to your configuration.  That lets it load for me, although the text still looks wrong.  I suspect this feed isn't actually in latin1, but instead has an incorrect encoding in the RSS header?

**Comment by thiagotalma** [comment]
Thank you for having solved the problem that caused the error.

Really now we have an encoding problem.

I think not be a problem in generating the feed, since we can open it without problems in the browser. Otherwise, we would see charsets errors in the browser.

**Comment by HyShai** [comment]
`<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">`

@cantino This solved the issue for me - can this be merged?

**Comment by cantino** [comment]
@HyShai, which issue did it solve for you?  The issue in this thread is of encoding on a feed being read into Huginn.

**Comment by HyShai** [comment]
@cantino oh whoops - it fixes the original issue of __New issue
Namespace prefix media on content is not defined.__

**Comment by cantino** [comment]
Oh, thanks @HyShai, I missed that.  Mind seeing if #1134 fixes everything for you?

**Comment by HyShai** [comment]
@cantino Yup #1134 fixes it. Thanks!

**Comment by cantino** [comment]
Thanks for checking @HyShai!

**Comment by eugenesvk** [comment]
@cantino I have a similar issue with **iTunes** style namespaces (e.g. `itunes:summary`).
I've tried adding `xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"` and created a PR for that, but your test routines all failed. Don't really understand what happened, so would you kindly check it out?

I've tried it on my **herokuapp** and it seems to be working, now I don't get error messages when I try to open the RSS XML output of the data output agent and instead have `<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">` displayed as in a proper .
Or should it be a stub declaration like `xmlns:itunes="http://search.yahoo.com/mrss/"` instead of the real one?

While I'm at it, would it be possible to adjust the `<channel>` declaration tags? As far as I understand, it only includes the default fields and re. the image there is only one default (`icon`), which doesn't get picked up in iTunes, so I don't see any images.
Ideally I'd like to
a) create a new tag in `<channel>` (e.g. `<itunes:image>`)
b) pass output of another agent in the value field (I have an agent that gets the url of the podcast image, so I want that passed to the output agent).
c) pass output of another agent to the default `<channel>` fields like `title` (so that I could pass the podcast title that my other agent pulled to that field instead of the default one or a manually entered one)

Thanks
